name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      ## 1. checkout & install
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install deps
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      ## 2. cache Nx computation results
      - uses: actions/cache@v4
        with:
          path: .nx/cache
          key: nx-${{ github.sha }}

      ## 3. run tests (all projects)
      - name: Nx tests
        run: pnpm nx run-many --target=test --all

      ## 4. build (all projects)
      - name: Nx build
        run: pnpm nx run-many --target=build --all

      ## 5. generate PlantUML docs (SVG)
      - name: Render PlantUML
        run: pnpm nx run-many --target=docs --all
